server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.139.155.223:3306/liferestart?serverTimezone=GMT%2b8
    username: root
    password: cqy374545

mybatis:
  mapper-locations: classpath:mapper/*.xml